# Generated by Django 5.0.1 on 2024-03-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='time_exec',
            field=models.TimeField(blank=True, default='00:02', null=True, verbose_name='время на выполнение'),
        ),
    ]
