# Generated by Django 5.0.1 on 2024-03-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habits_time_exec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habits',
            options={'ordering': ['name', 'place', 'action'], 'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
    ]
